version: '3.8'
services:
  back-end:
    build: ./backend
    container_name: backend_c
    ports: 
      - "3001:3001"
    volumes:
      - ./backend:/back
      - ./back/node_modules
  front-end:
    build:  ./frontend
    container_name: frontend_c
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - ./app/node_modules
    stdin_open: true
    tty: true